disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - vertical_whitespace
  - trailing_whitespace
  - force_cast
  - line_length
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - ProMed/SwiftyJSON.swift
